# .github/workflows/release.yml
name: release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'New tag name'
        required: true

# ...

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create tag
        run: |
          git tag ${{ github.event.inputs.tag }}
          git push --tags
      - name: Build and push Docker image
        run: |
          docker login --username vitalyisaev2 --password ${{ secrets.GHCR_TOKEN }} ghcr.io
          docker build -t ghcr.io/ydb-platform/fq-connector-go:${{ github.event.inputs.tag }} .
          docker push ghcr.io/ydb-platform/fq-connector-go:${{ github.event.inputs.tag }}
      # other steps bellow as usual
